package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.ExpressCompanyDO;
import com.lawu.eshop.mall.srv.domain.ExpressCompanyDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ExpressCompanyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int countByExample(ExpressCompanyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int deleteByExample(ExpressCompanyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int insert(ExpressCompanyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int insertSelective(ExpressCompanyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    List<ExpressCompanyDO> selectByExampleWithRowbounds(ExpressCompanyDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    List<ExpressCompanyDO> selectByExample(ExpressCompanyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    ExpressCompanyDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByExampleSelective(@Param("record") ExpressCompanyDO record, @Param("example") ExpressCompanyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByExample(@Param("record") ExpressCompanyDO record, @Param("example") ExpressCompanyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByPrimaryKeySelective(ExpressCompanyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByPrimaryKey(ExpressCompanyDO record);
}