package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.OnlineActivityImageDO;
import com.lawu.eshop.mall.srv.domain.OnlineActivityImageDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OnlineActivityImageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int countByExample(OnlineActivityImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int deleteByExample(OnlineActivityImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int insert(OnlineActivityImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int insertSelective(OnlineActivityImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    List<OnlineActivityImageDO> selectByExampleWithRowbounds(OnlineActivityImageDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    List<OnlineActivityImageDO> selectByExample(OnlineActivityImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    OnlineActivityImageDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByExampleSelective(@Param("record") OnlineActivityImageDO record, @Param("example") OnlineActivityImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByExample(@Param("record") OnlineActivityImageDO record, @Param("example") OnlineActivityImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByPrimaryKeySelective(OnlineActivityImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByPrimaryKey(OnlineActivityImageDO record);
}