package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.OnlineActivityDO;
import com.lawu.eshop.mall.srv.domain.OnlineActivityDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OnlineActivityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int countByExample(OnlineActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int deleteByExample(OnlineActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int insert(OnlineActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int insertSelective(OnlineActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    List<OnlineActivityDO> selectByExampleWithRowbounds(OnlineActivityDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    List<OnlineActivityDO> selectByExample(OnlineActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    OnlineActivityDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByExampleSelective(@Param("record") OnlineActivityDO record, @Param("example") OnlineActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByExample(@Param("record") OnlineActivityDO record, @Param("example") OnlineActivityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByPrimaryKeySelective(OnlineActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByPrimaryKey(OnlineActivityDO record);
}