package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.RegionDO;
import com.lawu.eshop.mall.srv.domain.RegionDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RegionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int countByExample(RegionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int deleteByExample(RegionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int insert(RegionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int insertSelective(RegionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    List<RegionDO> selectByExampleWithRowbounds(RegionDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    List<RegionDO> selectByExample(RegionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    RegionDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByExampleSelective(@Param("record") RegionDO record, @Param("example") RegionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByExample(@Param("record") RegionDO record, @Param("example") RegionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByPrimaryKeySelective(RegionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    int updateByPrimaryKey(RegionDO record);
}