package com.lawu.eshop.mall.srv.mapper;

import com.lawu.eshop.mall.srv.domain.SmsRecordDO;
import com.lawu.eshop.mall.srv.domain.SmsRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SmsRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int countByExample(SmsRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int deleteByExample(SmsRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int insert(SmsRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int insertSelective(SmsRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    List<SmsRecordDO> selectByExampleWithRowbounds(SmsRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    List<SmsRecordDO> selectByExample(SmsRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    SmsRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByExampleSelective(@Param("record") SmsRecordDO record, @Param("example") SmsRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByExample(@Param("record") SmsRecordDO record, @Param("example") SmsRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByPrimaryKeySelective(SmsRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_record
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    int updateByPrimaryKey(SmsRecordDO record);
}