package com.lawu.eshop.product.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProductDO implements Serializable {
    /**
     *
     * 主键
     * product.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 商家ID
     * product.merchant_id
     *
     * @mbg.generated
     */
    private Long merchantId;

    /**
     *
     * 分类ID
     * product.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * 编号
     * product.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * 名称
     * product.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * 特征图片
     * product.feature_image
     *
     * @mbg.generated
     */
    private String featureImage;

    /**
     *
     * 平均日销售
     * product.average_daily_sales
     *
     * @mbg.generated
     */
    private BigDecimal averageDailySales;

    /**
     *
     * 状态(1-删除2-上架3-下架)
     * product.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 是否支持退换货(0-否1-是)
     * product.is_allow_refund
     *
     * @mbg.generated
     */
    private Boolean isAllowRefund;

    /**
     *
     * 商品总库存
     * product.total_inventory
     *
     * @mbg.generated
     */
    private Integer totalInventory;

    /**
     *
     * 商品总销量
     * product.total_sales_volume
     *
     * @mbg.generated
     */
    private Integer totalSalesVolume;

    /**
     *
     * 总收藏
     * product.total_favorite
     *
     * @mbg.generated
     */
    private Integer totalFavorite;

    /**
     *
     * 型号最低价
     * product.min_price
     *
     * @mbg.generated
     */
    private BigDecimal minPrice;

    /**
     *
     * 型号最高价
     * product.max_price
     *
     * @mbg.generated
     */
    private BigDecimal maxPrice;

    /**
     *
     * 修改时间
     * product.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * product.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * 详细描述
     * product.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * 商品详情图片描述
     * product.image_content
     *
     * @mbg.generated
     */
    private String imageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.merchant_id
     *
     * @return the value of product.merchant_id
     *
     * @mbg.generated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.merchant_id
     *
     * @param merchantId the value for product.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.num
     *
     * @return the value of product.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.num
     *
     * @param num the value for product.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.feature_image
     *
     * @return the value of product.feature_image
     *
     * @mbg.generated
     */
    public String getFeatureImage() {
        return featureImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.feature_image
     *
     * @param featureImage the value for product.feature_image
     *
     * @mbg.generated
     */
    public void setFeatureImage(String featureImage) {
        this.featureImage = featureImage == null ? null : featureImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.average_daily_sales
     *
     * @return the value of product.average_daily_sales
     *
     * @mbg.generated
     */
    public BigDecimal getAverageDailySales() {
        return averageDailySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.average_daily_sales
     *
     * @param averageDailySales the value for product.average_daily_sales
     *
     * @mbg.generated
     */
    public void setAverageDailySales(BigDecimal averageDailySales) {
        this.averageDailySales = averageDailySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_allow_refund
     *
     * @return the value of product.is_allow_refund
     *
     * @mbg.generated
     */
    public Boolean getIsAllowRefund() {
        return isAllowRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_allow_refund
     *
     * @param isAllowRefund the value for product.is_allow_refund
     *
     * @mbg.generated
     */
    public void setIsAllowRefund(Boolean isAllowRefund) {
        this.isAllowRefund = isAllowRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.total_inventory
     *
     * @return the value of product.total_inventory
     *
     * @mbg.generated
     */
    public Integer getTotalInventory() {
        return totalInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.total_inventory
     *
     * @param totalInventory the value for product.total_inventory
     *
     * @mbg.generated
     */
    public void setTotalInventory(Integer totalInventory) {
        this.totalInventory = totalInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.total_sales_volume
     *
     * @return the value of product.total_sales_volume
     *
     * @mbg.generated
     */
    public Integer getTotalSalesVolume() {
        return totalSalesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.total_sales_volume
     *
     * @param totalSalesVolume the value for product.total_sales_volume
     *
     * @mbg.generated
     */
    public void setTotalSalesVolume(Integer totalSalesVolume) {
        this.totalSalesVolume = totalSalesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.total_favorite
     *
     * @return the value of product.total_favorite
     *
     * @mbg.generated
     */
    public Integer getTotalFavorite() {
        return totalFavorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.total_favorite
     *
     * @param totalFavorite the value for product.total_favorite
     *
     * @mbg.generated
     */
    public void setTotalFavorite(Integer totalFavorite) {
        this.totalFavorite = totalFavorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.min_price
     *
     * @return the value of product.min_price
     *
     * @mbg.generated
     */
    public BigDecimal getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.min_price
     *
     * @param minPrice the value for product.min_price
     *
     * @mbg.generated
     */
    public void setMinPrice(BigDecimal minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.max_price
     *
     * @return the value of product.max_price
     *
     * @mbg.generated
     */
    public BigDecimal getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.max_price
     *
     * @param maxPrice the value for product.max_price
     *
     * @mbg.generated
     */
    public void setMaxPrice(BigDecimal maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_modified
     *
     * @return the value of product.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_modified
     *
     * @param gmtModified the value for product.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_create
     *
     * @return the value of product.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_create
     *
     * @param gmtCreate the value for product.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.content
     *
     * @return the value of product.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.content
     *
     * @param content the value for product.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.image_content
     *
     * @return the value of product.image_content
     *
     * @mbg.generated
     */
    public String getImageContent() {
        return imageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.image_content
     *
     * @param imageContent the value for product.image_content
     *
     * @mbg.generated
     */
    public void setImageContent(String imageContent) {
        this.imageContent = imageContent == null ? null : imageContent.trim();
    }
}