package com.lawu.eshop.product.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class ProductImageDO implements Serializable {
    /**
     *
     * 主键
     * product_image.id
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    private Long id;

    /**
     *
     * 商品ID
     * product_image.product_id
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    private Long productId;

    /**
     *
     * 图片路径
     * product_image.image_path
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    private String imagePath;

    /**
     *
     * 修改时间
     * product_image.gmt_modified
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * product_image.gmt_create
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.id
     *
     * @return the value of product_image.id
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.id
     *
     * @param id the value for product_image.id
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.product_id
     *
     * @return the value of product_image.product_id
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.product_id
     *
     * @param productId the value for product_image.product_id
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.image_path
     *
     * @return the value of product_image.image_path
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.image_path
     *
     * @param imagePath the value for product_image.image_path
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.gmt_modified
     *
     * @return the value of product_image.gmt_modified
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.gmt_modified
     *
     * @param gmtModified the value for product_image.gmt_modified
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.gmt_create
     *
     * @return the value of product_image.gmt_create
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.gmt_create
     *
     * @param gmtCreate the value for product_image.gmt_create
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}