package com.lawu.eshop.product.srv.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public ProductDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNull() {
            addCriterion("merchant_id is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNotNull() {
            addCriterion("merchant_id is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdEqualTo(Long value) {
            addCriterion("merchant_id =", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotEqualTo(Long value) {
            addCriterion("merchant_id <>", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThan(Long value) {
            addCriterion("merchant_id >", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("merchant_id >=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThan(Long value) {
            addCriterion("merchant_id <", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThanOrEqualTo(Long value) {
            addCriterion("merchant_id <=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIn(List<Long> values) {
            addCriterion("merchant_id in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotIn(List<Long> values) {
            addCriterion("merchant_id not in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdBetween(Long value1, Long value2) {
            addCriterion("merchant_id between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotBetween(Long value1, Long value2) {
            addCriterion("merchant_id not between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantNumIsNull() {
            addCriterion("merchant_num is null");
            return (Criteria) this;
        }

        public Criteria andMerchantNumIsNotNull() {
            addCriterion("merchant_num is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantNumEqualTo(String value) {
            addCriterion("merchant_num =", value, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumNotEqualTo(String value) {
            addCriterion("merchant_num <>", value, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumGreaterThan(String value) {
            addCriterion("merchant_num >", value, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_num >=", value, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumLessThan(String value) {
            addCriterion("merchant_num <", value, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumLessThanOrEqualTo(String value) {
            addCriterion("merchant_num <=", value, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumLike(String value) {
            addCriterion("merchant_num like", value, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumNotLike(String value) {
            addCriterion("merchant_num not like", value, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumIn(List<String> values) {
            addCriterion("merchant_num in", values, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumNotIn(List<String> values) {
            addCriterion("merchant_num not in", values, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumBetween(String value1, String value2) {
            addCriterion("merchant_num between", value1, value2, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andMerchantNumNotBetween(String value1, String value2) {
            addCriterion("merchant_num not between", value1, value2, "merchantNum");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Integer value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Integer value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Integer value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Integer value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Integer> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Integer> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andFeatureImageIsNull() {
            addCriterion("feature_image is null");
            return (Criteria) this;
        }

        public Criteria andFeatureImageIsNotNull() {
            addCriterion("feature_image is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureImageEqualTo(String value) {
            addCriterion("feature_image =", value, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageNotEqualTo(String value) {
            addCriterion("feature_image <>", value, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageGreaterThan(String value) {
            addCriterion("feature_image >", value, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageGreaterThanOrEqualTo(String value) {
            addCriterion("feature_image >=", value, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageLessThan(String value) {
            addCriterion("feature_image <", value, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageLessThanOrEqualTo(String value) {
            addCriterion("feature_image <=", value, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageLike(String value) {
            addCriterion("feature_image like", value, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageNotLike(String value) {
            addCriterion("feature_image not like", value, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageIn(List<String> values) {
            addCriterion("feature_image in", values, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageNotIn(List<String> values) {
            addCriterion("feature_image not in", values, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageBetween(String value1, String value2) {
            addCriterion("feature_image between", value1, value2, "featureImage");
            return (Criteria) this;
        }

        public Criteria andFeatureImageNotBetween(String value1, String value2) {
            addCriterion("feature_image not between", value1, value2, "featureImage");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesIsNull() {
            addCriterion("average_daily_sales is null");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesIsNotNull() {
            addCriterion("average_daily_sales is not null");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesEqualTo(BigDecimal value) {
            addCriterion("average_daily_sales =", value, "averageDailySales");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesNotEqualTo(BigDecimal value) {
            addCriterion("average_daily_sales <>", value, "averageDailySales");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesGreaterThan(BigDecimal value) {
            addCriterion("average_daily_sales >", value, "averageDailySales");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("average_daily_sales >=", value, "averageDailySales");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesLessThan(BigDecimal value) {
            addCriterion("average_daily_sales <", value, "averageDailySales");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("average_daily_sales <=", value, "averageDailySales");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesIn(List<BigDecimal> values) {
            addCriterion("average_daily_sales in", values, "averageDailySales");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesNotIn(List<BigDecimal> values) {
            addCriterion("average_daily_sales not in", values, "averageDailySales");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("average_daily_sales between", value1, value2, "averageDailySales");
            return (Criteria) this;
        }

        public Criteria andAverageDailySalesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("average_daily_sales not between", value1, value2, "averageDailySales");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundIsNull() {
            addCriterion("is_allow_refund is null");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundIsNotNull() {
            addCriterion("is_allow_refund is not null");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundEqualTo(Boolean value) {
            addCriterion("is_allow_refund =", value, "isAllowRefund");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundNotEqualTo(Boolean value) {
            addCriterion("is_allow_refund <>", value, "isAllowRefund");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundGreaterThan(Boolean value) {
            addCriterion("is_allow_refund >", value, "isAllowRefund");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_allow_refund >=", value, "isAllowRefund");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundLessThan(Boolean value) {
            addCriterion("is_allow_refund <", value, "isAllowRefund");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundLessThanOrEqualTo(Boolean value) {
            addCriterion("is_allow_refund <=", value, "isAllowRefund");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundIn(List<Boolean> values) {
            addCriterion("is_allow_refund in", values, "isAllowRefund");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundNotIn(List<Boolean> values) {
            addCriterion("is_allow_refund not in", values, "isAllowRefund");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundBetween(Boolean value1, Boolean value2) {
            addCriterion("is_allow_refund between", value1, value2, "isAllowRefund");
            return (Criteria) this;
        }

        public Criteria andIsAllowRefundNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_allow_refund not between", value1, value2, "isAllowRefund");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryIsNull() {
            addCriterion("total_inventory is null");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryIsNotNull() {
            addCriterion("total_inventory is not null");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryEqualTo(Integer value) {
            addCriterion("total_inventory =", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryNotEqualTo(Integer value) {
            addCriterion("total_inventory <>", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryGreaterThan(Integer value) {
            addCriterion("total_inventory >", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_inventory >=", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryLessThan(Integer value) {
            addCriterion("total_inventory <", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryLessThanOrEqualTo(Integer value) {
            addCriterion("total_inventory <=", value, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryIn(List<Integer> values) {
            addCriterion("total_inventory in", values, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryNotIn(List<Integer> values) {
            addCriterion("total_inventory not in", values, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryBetween(Integer value1, Integer value2) {
            addCriterion("total_inventory between", value1, value2, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalInventoryNotBetween(Integer value1, Integer value2) {
            addCriterion("total_inventory not between", value1, value2, "totalInventory");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeIsNull() {
            addCriterion("total_sales_volume is null");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeIsNotNull() {
            addCriterion("total_sales_volume is not null");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeEqualTo(Integer value) {
            addCriterion("total_sales_volume =", value, "totalSalesVolume");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeNotEqualTo(Integer value) {
            addCriterion("total_sales_volume <>", value, "totalSalesVolume");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeGreaterThan(Integer value) {
            addCriterion("total_sales_volume >", value, "totalSalesVolume");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_sales_volume >=", value, "totalSalesVolume");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeLessThan(Integer value) {
            addCriterion("total_sales_volume <", value, "totalSalesVolume");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeLessThanOrEqualTo(Integer value) {
            addCriterion("total_sales_volume <=", value, "totalSalesVolume");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeIn(List<Integer> values) {
            addCriterion("total_sales_volume in", values, "totalSalesVolume");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeNotIn(List<Integer> values) {
            addCriterion("total_sales_volume not in", values, "totalSalesVolume");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeBetween(Integer value1, Integer value2) {
            addCriterion("total_sales_volume between", value1, value2, "totalSalesVolume");
            return (Criteria) this;
        }

        public Criteria andTotalSalesVolumeNotBetween(Integer value1, Integer value2) {
            addCriterion("total_sales_volume not between", value1, value2, "totalSalesVolume");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteIsNull() {
            addCriterion("total_favorite is null");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteIsNotNull() {
            addCriterion("total_favorite is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteEqualTo(Integer value) {
            addCriterion("total_favorite =", value, "totalFavorite");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteNotEqualTo(Integer value) {
            addCriterion("total_favorite <>", value, "totalFavorite");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteGreaterThan(Integer value) {
            addCriterion("total_favorite >", value, "totalFavorite");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_favorite >=", value, "totalFavorite");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteLessThan(Integer value) {
            addCriterion("total_favorite <", value, "totalFavorite");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteLessThanOrEqualTo(Integer value) {
            addCriterion("total_favorite <=", value, "totalFavorite");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteIn(List<Integer> values) {
            addCriterion("total_favorite in", values, "totalFavorite");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteNotIn(List<Integer> values) {
            addCriterion("total_favorite not in", values, "totalFavorite");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteBetween(Integer value1, Integer value2) {
            addCriterion("total_favorite between", value1, value2, "totalFavorite");
            return (Criteria) this;
        }

        public Criteria andTotalFavoriteNotBetween(Integer value1, Integer value2) {
            addCriterion("total_favorite not between", value1, value2, "totalFavorite");
            return (Criteria) this;
        }

        public Criteria andMinPriceIsNull() {
            addCriterion("min_price is null");
            return (Criteria) this;
        }

        public Criteria andMinPriceIsNotNull() {
            addCriterion("min_price is not null");
            return (Criteria) this;
        }

        public Criteria andMinPriceEqualTo(BigDecimal value) {
            addCriterion("min_price =", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceNotEqualTo(BigDecimal value) {
            addCriterion("min_price <>", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceGreaterThan(BigDecimal value) {
            addCriterion("min_price >", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("min_price >=", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceLessThan(BigDecimal value) {
            addCriterion("min_price <", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("min_price <=", value, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceIn(List<BigDecimal> values) {
            addCriterion("min_price in", values, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceNotIn(List<BigDecimal> values) {
            addCriterion("min_price not in", values, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("min_price between", value1, value2, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMinPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("min_price not between", value1, value2, "minPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceIsNull() {
            addCriterion("max_price is null");
            return (Criteria) this;
        }

        public Criteria andMaxPriceIsNotNull() {
            addCriterion("max_price is not null");
            return (Criteria) this;
        }

        public Criteria andMaxPriceEqualTo(BigDecimal value) {
            addCriterion("max_price =", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceNotEqualTo(BigDecimal value) {
            addCriterion("max_price <>", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceGreaterThan(BigDecimal value) {
            addCriterion("max_price >", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("max_price >=", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceLessThan(BigDecimal value) {
            addCriterion("max_price <", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("max_price <=", value, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceIn(List<BigDecimal> values) {
            addCriterion("max_price in", values, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceNotIn(List<BigDecimal> values) {
            addCriterion("max_price not in", values, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_price between", value1, value2, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andMaxPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_price not between", value1, value2, "maxPrice");
            return (Criteria) this;
        }

        public Criteria andGmtDownIsNull() {
            addCriterion("gmt_down is null");
            return (Criteria) this;
        }

        public Criteria andGmtDownIsNotNull() {
            addCriterion("gmt_down is not null");
            return (Criteria) this;
        }

        public Criteria andGmtDownEqualTo(Date value) {
            addCriterion("gmt_down =", value, "gmtDown");
            return (Criteria) this;
        }

        public Criteria andGmtDownNotEqualTo(Date value) {
            addCriterion("gmt_down <>", value, "gmtDown");
            return (Criteria) this;
        }

        public Criteria andGmtDownGreaterThan(Date value) {
            addCriterion("gmt_down >", value, "gmtDown");
            return (Criteria) this;
        }

        public Criteria andGmtDownGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_down >=", value, "gmtDown");
            return (Criteria) this;
        }

        public Criteria andGmtDownLessThan(Date value) {
            addCriterion("gmt_down <", value, "gmtDown");
            return (Criteria) this;
        }

        public Criteria andGmtDownLessThanOrEqualTo(Date value) {
            addCriterion("gmt_down <=", value, "gmtDown");
            return (Criteria) this;
        }

        public Criteria andGmtDownIn(List<Date> values) {
            addCriterion("gmt_down in", values, "gmtDown");
            return (Criteria) this;
        }

        public Criteria andGmtDownNotIn(List<Date> values) {
            addCriterion("gmt_down not in", values, "gmtDown");
            return (Criteria) this;
        }

        public Criteria andGmtDownBetween(Date value1, Date value2) {
            addCriterion("gmt_down between", value1, value2, "gmtDown");
            return (Criteria) this;
        }

        public Criteria andGmtDownNotBetween(Date value1, Date value2) {
            addCriterion("gmt_down not between", value1, value2, "gmtDown");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}