package com.lawu.eshop.product.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class ProductDO implements Serializable {
    /**
     *
     * 主键
     * product.id
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private Long id;

    /**
     *
     * 商家ID
     * product.merchant_id
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private Long merchantId;

    /**
     *
     * 分类ID
     * product.category_id
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private Integer categoryId;

    /**
     *
     * 编号
     * product.num
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private String num;

    /**
     *
     * 名称
     * product.name
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private String name;

    /**
     *
     * 特征图片
     * product.feature_image
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private Long featureImage;

    /**
     *
     * 状态
     * product.status
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private Byte status;

    /**
     *
     * 修改时间
     * product.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * product.gmt_create
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private Date gmtCreate;

    /**
     *
     * 详细描述
     * product.content
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.merchant_id
     *
     * @return the value of product.merchant_id
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.merchant_id
     *
     * @param merchantId the value for product.merchant_id
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.num
     *
     * @return the value of product.num
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.num
     *
     * @param num the value for product.num
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.feature_image
     *
     * @return the value of product.feature_image
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public Long getFeatureImage() {
        return featureImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.feature_image
     *
     * @param featureImage the value for product.feature_image
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public void setFeatureImage(Long featureImage) {
        this.featureImage = featureImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_modified
     *
     * @return the value of product.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_modified
     *
     * @param gmtModified the value for product.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_create
     *
     * @return the value of product.gmt_create
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_create
     *
     * @param gmtCreate the value for product.gmt_create
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.content
     *
     * @return the value of product.content
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.content
     *
     * @param content the value for product.content
     *
     * @mbg.generated 2017-03-22 02:35:01
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}