package com.lawu.eshop.product.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProductModelDO implements Serializable {
    /**
     *
     * 主键
     * product_model.id
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private Long id;

    /**
     *
     * 商家ID
     * product_model.merchant_id
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private Long merchantId;

    /**
     *
     * 商品ID
     * product_model.product_id
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private Long productId;

    /**
     *
     * 编号
     * product_model.num
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private String num;

    /**
     *
     * 名称
     * product_model.name
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private String name;

    /**
     *
     * 原价
     * product_model.original_price
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private BigDecimal originalPrice;

    /**
     *
     * 现价
     * product_model.price
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private BigDecimal price;

    /**
     *
     * 销量
     * product_model.sales_volume
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private Integer salesVolume;

    /**
     *
     * 库存
     * product_model.inventory
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private Integer inventory;

    /**
     *
     * 状态(0-删除1-有效)
     * product_model.status
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private Boolean status;

    /**
     *
     * 修改时间
     * product_model.gmt_modified
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * product_model.gmt_create
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.id
     *
     * @return the value of product_model.id
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.id
     *
     * @param id the value for product_model.id
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.merchant_id
     *
     * @return the value of product_model.merchant_id
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.merchant_id
     *
     * @param merchantId the value for product_model.merchant_id
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.product_id
     *
     * @return the value of product_model.product_id
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.product_id
     *
     * @param productId the value for product_model.product_id
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.num
     *
     * @return the value of product_model.num
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.num
     *
     * @param num the value for product_model.num
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.name
     *
     * @return the value of product_model.name
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.name
     *
     * @param name the value for product_model.name
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.original_price
     *
     * @return the value of product_model.original_price
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.original_price
     *
     * @param originalPrice the value for product_model.original_price
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.price
     *
     * @return the value of product_model.price
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.price
     *
     * @param price the value for product_model.price
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.sales_volume
     *
     * @return the value of product_model.sales_volume
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public Integer getSalesVolume() {
        return salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.sales_volume
     *
     * @param salesVolume the value for product_model.sales_volume
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setSalesVolume(Integer salesVolume) {
        this.salesVolume = salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.inventory
     *
     * @return the value of product_model.inventory
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.inventory
     *
     * @param inventory the value for product_model.inventory
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.status
     *
     * @return the value of product_model.status
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.status
     *
     * @param status the value for product_model.status
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.gmt_modified
     *
     * @return the value of product_model.gmt_modified
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.gmt_modified
     *
     * @param gmtModified the value for product_model.gmt_modified
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_model.gmt_create
     *
     * @return the value of product_model.gmt_create
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_model.gmt_create
     *
     * @param gmtCreate the value for product_model.gmt_create
     *
     * @mbg.generated 2017-03-28 16:15:49
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}