package com.lawu.eshop.statistics.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ReportWithdrawMonthDO implements Serializable {
    /**
     *
     * 主键
     * report_withdraw_month.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 提现成功金额(含手续费)
     * report_withdraw_month.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     *
     * 用户类型(1-用户2-商家)
     * report_withdraw_month.user_type
     *
     * @mbg.generated
     */
    private Byte userType;

    /**
     *
     * 统计数据所属日期
     * report_withdraw_month.gmt_report
     *
     * @mbg.generated
     */
    private Date gmtReport;

    /**
     *
     * 统计时间
     * report_withdraw_month.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_withdraw_month
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_withdraw_month.id
     *
     * @return the value of report_withdraw_month.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_withdraw_month.id
     *
     * @param id the value for report_withdraw_month.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_withdraw_month.money
     *
     * @return the value of report_withdraw_month.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_withdraw_month.money
     *
     * @param money the value for report_withdraw_month.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_withdraw_month.user_type
     *
     * @return the value of report_withdraw_month.user_type
     *
     * @mbg.generated
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_withdraw_month.user_type
     *
     * @param userType the value for report_withdraw_month.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_withdraw_month.gmt_report
     *
     * @return the value of report_withdraw_month.gmt_report
     *
     * @mbg.generated
     */
    public Date getGmtReport() {
        return gmtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_withdraw_month.gmt_report
     *
     * @param gmtReport the value for report_withdraw_month.gmt_report
     *
     * @mbg.generated
     */
    public void setGmtReport(Date gmtReport) {
        this.gmtReport = gmtReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_withdraw_month.gmt_create
     *
     * @return the value of report_withdraw_month.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_withdraw_month.gmt_create
     *
     * @param gmtCreate the value for report_withdraw_month.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}