package com.lawu.eshop.property.srv.mapper;

import com.lawu.eshop.property.srv.domain.BankAccountDO;
import com.lawu.eshop.property.srv.domain.BankAccountDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BankAccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    int countByExample(BankAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    int deleteByExample(BankAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    int insert(BankAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    int insertSelective(BankAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    List<BankAccountDO> selectByExampleWithRowbounds(BankAccountDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    List<BankAccountDO> selectByExample(BankAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    BankAccountDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    int updateByExampleSelective(@Param("record") BankAccountDO record, @Param("example") BankAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    int updateByExample(@Param("record") BankAccountDO record, @Param("example") BankAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    int updateByPrimaryKeySelective(BankAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    int updateByPrimaryKey(BankAccountDO record);
}