package com.lawu.eshop.property.srv.mapper;

import com.lawu.eshop.property.srv.domain.BankDO;
import com.lawu.eshop.property.srv.domain.BankDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BankDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    int countByExample(BankDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    int deleteByExample(BankDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    int insert(BankDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    int insertSelective(BankDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    List<BankDO> selectByExampleWithRowbounds(BankDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    List<BankDO> selectByExample(BankDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    BankDO selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    int updateByExampleSelective(@Param("record") BankDO record, @Param("example") BankDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    int updateByExample(@Param("record") BankDO record, @Param("example") BankDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    int updateByPrimaryKeySelective(BankDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank
     *
     * @mbg.generated 2017-03-24 10:40:46
     */
    int updateByPrimaryKey(BankDO record);
}