package com.lawu.eshop.property.srv.mapper;

import com.lawu.eshop.property.srv.domain.PointDetailDO;
import com.lawu.eshop.property.srv.domain.PointDetailDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PointDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    int countByExample(PointDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    int deleteByExample(PointDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    int insert(PointDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    int insertSelective(PointDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    List<PointDetailDO> selectByExampleWithRowbounds(PointDetailDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    List<PointDetailDO> selectByExample(PointDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    PointDetailDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    int updateByExampleSelective(@Param("record") PointDetailDO record, @Param("example") PointDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    int updateByExample(@Param("record") PointDetailDO record, @Param("example") PointDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    int updateByPrimaryKeySelective(PointDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-28 15:08:46
     */
    int updateByPrimaryKey(PointDetailDO record);
}