package com.lawu.eshop.product.srv.mapper;

import com.lawu.eshop.product.srv.domain.ProductCategoryeDO;
import com.lawu.eshop.product.srv.domain.ProductCategoryeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProductCategoryeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int countByExample(ProductCategoryeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int deleteByExample(ProductCategoryeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int insert(ProductCategoryeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int insertSelective(ProductCategoryeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    List<ProductCategoryeDO> selectByExampleWithRowbounds(ProductCategoryeDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    List<ProductCategoryeDO> selectByExample(ProductCategoryeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    ProductCategoryeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByExampleSelective(@Param("record") ProductCategoryeDO record, @Param("example") ProductCategoryeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByExample(@Param("record") ProductCategoryeDO record, @Param("example") ProductCategoryeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByPrimaryKeySelective(ProductCategoryeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByPrimaryKey(ProductCategoryeDO record);
}