package com.lawu.eshop.product.srv.mapper;

import com.lawu.eshop.product.srv.domain.ProductModelDO;
import com.lawu.eshop.product.srv.domain.ProductModelDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProductModelDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int countByExample(ProductModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int deleteByExample(ProductModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int insert(ProductModelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int insertSelective(ProductModelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    List<ProductModelDO> selectByExampleWithRowbounds(ProductModelDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    List<ProductModelDO> selectByExample(ProductModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    ProductModelDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByExampleSelective(@Param("record") ProductModelDO record, @Param("example") ProductModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByExample(@Param("record") ProductModelDO record, @Param("example") ProductModelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByPrimaryKeySelective(ProductModelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_model
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByPrimaryKey(ProductModelDO record);
}