package com.lawu.eshop.product.srv.mapper;

import com.lawu.eshop.product.srv.domain.ProductImageDO;
import com.lawu.eshop.product.srv.domain.ProductImageDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProductImageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int countByExample(ProductImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int deleteByExample(ProductImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int insert(ProductImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int insertSelective(ProductImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    List<ProductImageDO> selectByExampleWithRowbounds(ProductImageDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    List<ProductImageDO> selectByExample(ProductImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    ProductImageDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByExampleSelective(@Param("record") ProductImageDO record, @Param("example") ProductImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByExample(@Param("record") ProductImageDO record, @Param("example") ProductImageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByPrimaryKeySelective(ProductImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated 2017-03-23 17:10:02
     */
    int updateByPrimaryKey(ProductImageDO record);
}