package com.lawu.eshop.mall.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class ExpressCompanyDO implements Serializable {
    /**
     *
     * 主键
     * express_company.id
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Integer id;

    /**
     *
     * 编码
     * express_company.code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private String code;

    /**
     *
     * 名称
     * express_company.name
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private String name;

    /**
     *
     * 网址
     * express_company.homepage
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private String homepage;

    /**
     *
     * 电话
     * express_company.tel
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private String tel;

    /**
     *
     * 排序
     * express_company.ordinal
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Integer ordinal;

    /**
     *
     * 状态
     * express_company.status
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Byte status;

    /**
     *
     * 修改时间
     * express_company.gmt_modified
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * express_company.gmt_create
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table express_company
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.id
     *
     * @return the value of express_company.id
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.id
     *
     * @param id the value for express_company.id
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.code
     *
     * @return the value of express_company.code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.code
     *
     * @param code the value for express_company.code
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.name
     *
     * @return the value of express_company.name
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.name
     *
     * @param name the value for express_company.name
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.homepage
     *
     * @return the value of express_company.homepage
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.homepage
     *
     * @param homepage the value for express_company.homepage
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage == null ? null : homepage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.tel
     *
     * @return the value of express_company.tel
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.tel
     *
     * @param tel the value for express_company.tel
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.ordinal
     *
     * @return the value of express_company.ordinal
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Integer getOrdinal() {
        return ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.ordinal
     *
     * @param ordinal the value for express_company.ordinal
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setOrdinal(Integer ordinal) {
        this.ordinal = ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.status
     *
     * @return the value of express_company.status
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.status
     *
     * @param status the value for express_company.status
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.gmt_modified
     *
     * @return the value of express_company.gmt_modified
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.gmt_modified
     *
     * @param gmtModified the value for express_company.gmt_modified
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_company.gmt_create
     *
     * @return the value of express_company.gmt_create
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_company.gmt_create
     *
     * @param gmtCreate the value for express_company.gmt_create
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}