package com.lawu.eshop.mall.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class IndustryTypeDO implements Serializable {
    /**
     *
     * 主键
     * industry_type.id
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Integer id;

    /**
     *
     * 父编号
     * industry_type.parent_id
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Short parentId;

    /**
     *
     * 行业路径
     * industry_type.path
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private String path;

    /**
     *
     * 行业名称
     * industry_type.name
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private String name;

    /**
     *
     * 序号
     * industry_type.ordinal
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Integer ordinal;

    /**
     *
     * 1为启用,0为停用
     * industry_type.status
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Byte status;

    /**
     *
     * 修改时间
     * industry_type.gmt_modified
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * industry_type.gmt_create
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table industry_type
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.id
     *
     * @return the value of industry_type.id
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.id
     *
     * @param id the value for industry_type.id
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.parent_id
     *
     * @return the value of industry_type.parent_id
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Short getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.parent_id
     *
     * @param parentId the value for industry_type.parent_id
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setParentId(Short parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.path
     *
     * @return the value of industry_type.path
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.path
     *
     * @param path the value for industry_type.path
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.name
     *
     * @return the value of industry_type.name
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.name
     *
     * @param name the value for industry_type.name
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.ordinal
     *
     * @return the value of industry_type.ordinal
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Integer getOrdinal() {
        return ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.ordinal
     *
     * @param ordinal the value for industry_type.ordinal
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setOrdinal(Integer ordinal) {
        this.ordinal = ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.status
     *
     * @return the value of industry_type.status
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.status
     *
     * @param status the value for industry_type.status
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.gmt_modified
     *
     * @return the value of industry_type.gmt_modified
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.gmt_modified
     *
     * @param gmtModified the value for industry_type.gmt_modified
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column industry_type.gmt_create
     *
     * @return the value of industry_type.gmt_create
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column industry_type.gmt_create
     *
     * @param gmtCreate the value for industry_type.gmt_create
     *
     * @mbg.generated 2017-03-27 11:22:59
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}