package com.lawu.eshop.mall.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class MessageDO implements Serializable {
    /**
     *
     * 主键
     * message.id
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private Long id;

    /**
     *
     * 用户编号
     * message.user_num
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private String userNum;

    /**
     *
     * 关联主键
     * message.relate_id
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private Long relateId;

    /**
     *
     * 消息类型
     * message.type
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private Byte type;

    /**
     *
     * 消息内容
     * message.content
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private String content;

    /**
     *
     * 状态：0未读，1已读，2删除
     * message.status
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private Byte status;

    /**
     *
     * 修改时间
     * message.gmt_modified
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * message.gmt_create
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_num
     *
     * @return the value of message.user_num
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.user_num
     *
     * @param userNum the value for message.user_num
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.relate_id
     *
     * @return the value of message.relate_id
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public Long getRelateId() {
        return relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.relate_id
     *
     * @param relateId the value for message.relate_id
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setRelateId(Long relateId) {
        this.relateId = relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.gmt_modified
     *
     * @return the value of message.gmt_modified
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.gmt_modified
     *
     * @param gmtModified the value for message.gmt_modified
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.gmt_create
     *
     * @return the value of message.gmt_create
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.gmt_create
     *
     * @param gmtCreate the value for message.gmt_create
     *
     * @mbg.generated 2017-03-29 11:30:47
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}