package com.lawu.eshop.mall.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class OnlineActivityDO implements Serializable {
    /**
     *
     * 主键
     * online_activity.id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private Long id;

    /**
     *
     * 商家ID
     * online_activity.merchant_id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private Long merchantId;

    /**
     *
     * 活动标题
     * online_activity.title
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private String title;

    /**
     *
     * 活动摘要
     * online_activity.summary
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private String summary;

    /**
     *
     * 活动内容
     * online_activity.content
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private String content;

    /**
     *
     * 0草稿 1上架 2撤销
     * online_activity.status
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private Byte status;

    /**
     *
     * 修改时间
     * online_activity.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * online_activity.gmt_create
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table online_activity
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity.id
     *
     * @return the value of online_activity.id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity.id
     *
     * @param id the value for online_activity.id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity.merchant_id
     *
     * @return the value of online_activity.merchant_id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity.merchant_id
     *
     * @param merchantId the value for online_activity.merchant_id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity.title
     *
     * @return the value of online_activity.title
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity.title
     *
     * @param title the value for online_activity.title
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity.summary
     *
     * @return the value of online_activity.summary
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity.summary
     *
     * @param summary the value for online_activity.summary
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity.content
     *
     * @return the value of online_activity.content
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity.content
     *
     * @param content the value for online_activity.content
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity.status
     *
     * @return the value of online_activity.status
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity.status
     *
     * @param status the value for online_activity.status
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity.gmt_modified
     *
     * @return the value of online_activity.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity.gmt_modified
     *
     * @param gmtModified the value for online_activity.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity.gmt_create
     *
     * @return the value of online_activity.gmt_create
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity.gmt_create
     *
     * @param gmtCreate the value for online_activity.gmt_create
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}