package com.lawu.eshop.mall.srv.domain;

import java.io.Serializable;

public class OnlineActivityImageDO implements Serializable {
    /**
     *
     * 主键
     * online_activity_image.id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private Long id;

    /**
     *
     * 活动ID
     * online_activity_image.online_activity_id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private Long onlineActivityId;

    /**
     *
     * 图片地址
     * online_activity_image.image_url
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table online_activity_image
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity_image.id
     *
     * @return the value of online_activity_image.id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity_image.id
     *
     * @param id the value for online_activity_image.id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity_image.online_activity_id
     *
     * @return the value of online_activity_image.online_activity_id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public Long getOnlineActivityId() {
        return onlineActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity_image.online_activity_id
     *
     * @param onlineActivityId the value for online_activity_image.online_activity_id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setOnlineActivityId(Long onlineActivityId) {
        this.onlineActivityId = onlineActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_activity_image.image_url
     *
     * @return the value of online_activity_image.image_url
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_activity_image.image_url
     *
     * @param imageUrl the value for online_activity_image.image_url
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }
}