package com.lawu.eshop.mall.srv.domain;

import java.io.Serializable;

public class RegionDO implements Serializable {
    /**
     *
     * 区域ID
     * region.id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private Integer id;

    /**
     *
     * 父级区域
     * region.parent_id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private Integer parentId;

    /**
     *
     * 路径
     * region.path
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private String path;

    /**
     *
     * 层级
     * region.level
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private Byte level;

    /**
     *
     * 区域名称
     * region.name
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table region
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.id
     *
     * @return the value of region.id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.id
     *
     * @param id the value for region.id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.parent_id
     *
     * @return the value of region.parent_id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.parent_id
     *
     * @param parentId the value for region.parent_id
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.path
     *
     * @return the value of region.path
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.path
     *
     * @param path the value for region.path
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.level
     *
     * @return the value of region.level
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.level
     *
     * @param level the value for region.level
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.name
     *
     * @return the value of region.name
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.name
     *
     * @param name the value for region.name
     *
     * @mbg.generated 2017-03-22 02:41:06
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}