package com.lawu.eshop.mall.srv.domain;

import java.io.Serializable;

public class TradeDO implements Serializable {
    /**
     *
     * 主键
     * trade.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * 父编号
     * trade.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * 行业路径
     * trade.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * 行业名称
     * trade.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * 类别等级
     * trade.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.id
     *
     * @return the value of trade.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.id
     *
     * @param id the value for trade.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.parent_id
     *
     * @return the value of trade.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.parent_id
     *
     * @param parentId the value for trade.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.path
     *
     * @return the value of trade.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.path
     *
     * @param path the value for trade.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.name
     *
     * @return the value of trade.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.name
     *
     * @param name the value for trade.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.level
     *
     * @return the value of trade.level
     *
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.level
     *
     * @param level the value for trade.level
     *
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }
}