package com.lawu.eshop.property.srv.domain;

import java.io.Serializable;

public class BankAccountDO implements Serializable {
    /**
     *
     * 主键
     * bank_account.id
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private Long id;

    /**
     *
     * 用户编号
     * bank_account.user_num
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private String userNum;

    /**
     *
     * 用户名
     * bank_account.account_name
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private String accountName;

    /**
     *
     * 账号
     * bank_account.account_number
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private String accountNumber;

    /**
     *
     * 开户行
     * bank_account.bank_id
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private Integer bankId;

    /**
     *
     * 支行
     * bank_account.sub_branch_name
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private String subBranchName;

    /**
     *
     * 1启用 2停用 3删除
     * bank_account.status
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private Byte status;

    /**
     *
     * 备注
     * bank_account.note
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.id
     *
     * @return the value of bank_account.id
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.id
     *
     * @param id the value for bank_account.id
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.user_num
     *
     * @return the value of bank_account.user_num
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.user_num
     *
     * @param userNum the value for bank_account.user_num
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.account_name
     *
     * @return the value of bank_account.account_name
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.account_name
     *
     * @param accountName the value for bank_account.account_name
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.account_number
     *
     * @return the value of bank_account.account_number
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.account_number
     *
     * @param accountNumber the value for bank_account.account_number
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber == null ? null : accountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.bank_id
     *
     * @return the value of bank_account.bank_id
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.bank_id
     *
     * @param bankId the value for bank_account.bank_id
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.sub_branch_name
     *
     * @return the value of bank_account.sub_branch_name
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public String getSubBranchName() {
        return subBranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.sub_branch_name
     *
     * @param subBranchName the value for bank_account.sub_branch_name
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setSubBranchName(String subBranchName) {
        this.subBranchName = subBranchName == null ? null : subBranchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.status
     *
     * @return the value of bank_account.status
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.status
     *
     * @param status the value for bank_account.status
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account.note
     *
     * @return the value of bank_account.note
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account.note
     *
     * @param note the value for bank_account.note
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}