package com.lawu.eshop.property.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class LoveDetailDO implements Serializable {
    /**
     *
     * 主键
     * love_detail.id
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private Long id;

    /**
     *
     * 爱心标题
     * love_detail.title
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private String title;

    /**
     *
     * 爱心编号
     * love_detail.love_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private String loveNum;

    /**
     *
     * 用户编号
     * love_detail.user_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private String userNum;

    /**
     *
     * 爱心来源类型
     * love_detail.love_type
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private Byte loveType;

    /**
     *
     * 金额
     * love_detail.amount
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private BigDecimal amount;

    /**
     *
     * 备注
     * love_detail.remark
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private String remark;

    /**
     *
     * 创建时间
     * love_detail.gmt_create
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table love_detail
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_detail.id
     *
     * @return the value of love_detail.id
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_detail.id
     *
     * @param id the value for love_detail.id
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_detail.title
     *
     * @return the value of love_detail.title
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_detail.title
     *
     * @param title the value for love_detail.title
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_detail.love_num
     *
     * @return the value of love_detail.love_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public String getLoveNum() {
        return loveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_detail.love_num
     *
     * @param loveNum the value for love_detail.love_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setLoveNum(String loveNum) {
        this.loveNum = loveNum == null ? null : loveNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_detail.user_num
     *
     * @return the value of love_detail.user_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_detail.user_num
     *
     * @param userNum the value for love_detail.user_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_detail.love_type
     *
     * @return the value of love_detail.love_type
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public Byte getLoveType() {
        return loveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_detail.love_type
     *
     * @param loveType the value for love_detail.love_type
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setLoveType(Byte loveType) {
        this.loveType = loveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_detail.amount
     *
     * @return the value of love_detail.amount
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_detail.amount
     *
     * @param amount the value for love_detail.amount
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_detail.remark
     *
     * @return the value of love_detail.remark
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_detail.remark
     *
     * @param remark the value for love_detail.remark
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column love_detail.gmt_create
     *
     * @return the value of love_detail.gmt_create
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column love_detail.gmt_create
     *
     * @param gmtCreate the value for love_detail.gmt_create
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}