package com.lawu.eshop.property.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class PointDetailDO implements Serializable {
    /**
     *
     * 主键
     * point_detail.id
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private Long id;

    /**
     *
     * 积分标题
     * point_detail.title
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private String title;

    /**
     *
     * 积分编号
     * point_detail.point_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private String pointNum;

    /**
     *
     * 用户编号
     * point_detail.user_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private String userNum;

    /**
     *
     * 积分类型
     * point_detail.point_type
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private Byte pointType;

    /**
     *
     * 积分
     * point_detail.point
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private Integer point;

    /**
     *
     * 备注
     * point_detail.remark
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private String remark;

    /**
     *
     * 创建时间
     * point_detail.gmt_create
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table point_detail
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.id
     *
     * @return the value of point_detail.id
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.id
     *
     * @param id the value for point_detail.id
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.title
     *
     * @return the value of point_detail.title
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.title
     *
     * @param title the value for point_detail.title
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.point_num
     *
     * @return the value of point_detail.point_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public String getPointNum() {
        return pointNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.point_num
     *
     * @param pointNum the value for point_detail.point_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setPointNum(String pointNum) {
        this.pointNum = pointNum == null ? null : pointNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.user_num
     *
     * @return the value of point_detail.user_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.user_num
     *
     * @param userNum the value for point_detail.user_num
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.point_type
     *
     * @return the value of point_detail.point_type
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public Byte getPointType() {
        return pointType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.point_type
     *
     * @param pointType the value for point_detail.point_type
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setPointType(Byte pointType) {
        this.pointType = pointType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.point
     *
     * @return the value of point_detail.point
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.point
     *
     * @param point the value for point_detail.point
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.remark
     *
     * @return the value of point_detail.remark
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.remark
     *
     * @param remark the value for point_detail.remark
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_detail.gmt_create
     *
     * @return the value of point_detail.gmt_create
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_detail.gmt_create
     *
     * @param gmtCreate the value for point_detail.gmt_create
     *
     * @mbg.generated 2017-03-30 16:44:14
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}