package com.lawu.eshop.property.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TransactionDetailDO implements Serializable {
    /**
     *
     * 主键
     * transaction_detail.id
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private Long id;

    /**
     *
     * 交易标题
     * transaction_detail.title
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private String title;

    /**
     *
     * 交易编号
     * transaction_detail.transaction_num
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private String transactionNum;

    /**
     *
     * 用户编号
     * transaction_detail.user_num
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private String userNum;

    /**
     *
     * 交易类型
     * transaction_detail.transaction_type
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private Byte transactionType;

    /**
     *
     * 交易账户
     * transaction_detail.transaction_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private String transactionAccount;

    /**
     *
     * 交易账户类型
     * transaction_detail.transaction_account_type
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private Byte transactionAccountType;

    /**
     *
     * 金额
     * transaction_detail.amount
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private BigDecimal amount;

    /**
     *
     * 备注
     * transaction_detail.remark
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private String remark;

    /**
     *
     * 创建时间
     * transaction_detail.gmt_create
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transaction_detail
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_detail.id
     *
     * @return the value of transaction_detail.id
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_detail.id
     *
     * @param id the value for transaction_detail.id
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_detail.title
     *
     * @return the value of transaction_detail.title
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_detail.title
     *
     * @param title the value for transaction_detail.title
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_detail.transaction_num
     *
     * @return the value of transaction_detail.transaction_num
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public String getTransactionNum() {
        return transactionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_detail.transaction_num
     *
     * @param transactionNum the value for transaction_detail.transaction_num
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setTransactionNum(String transactionNum) {
        this.transactionNum = transactionNum == null ? null : transactionNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_detail.user_num
     *
     * @return the value of transaction_detail.user_num
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_detail.user_num
     *
     * @param userNum the value for transaction_detail.user_num
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_detail.transaction_type
     *
     * @return the value of transaction_detail.transaction_type
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public Byte getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_detail.transaction_type
     *
     * @param transactionType the value for transaction_detail.transaction_type
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setTransactionType(Byte transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_detail.transaction_account
     *
     * @return the value of transaction_detail.transaction_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public String getTransactionAccount() {
        return transactionAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_detail.transaction_account
     *
     * @param transactionAccount the value for transaction_detail.transaction_account
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setTransactionAccount(String transactionAccount) {
        this.transactionAccount = transactionAccount == null ? null : transactionAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_detail.transaction_account_type
     *
     * @return the value of transaction_detail.transaction_account_type
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public Byte getTransactionAccountType() {
        return transactionAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_detail.transaction_account_type
     *
     * @param transactionAccountType the value for transaction_detail.transaction_account_type
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setTransactionAccountType(Byte transactionAccountType) {
        this.transactionAccountType = transactionAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_detail.amount
     *
     * @return the value of transaction_detail.amount
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_detail.amount
     *
     * @param amount the value for transaction_detail.amount
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_detail.remark
     *
     * @return the value of transaction_detail.remark
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_detail.remark
     *
     * @param remark the value for transaction_detail.remark
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_detail.gmt_create
     *
     * @return the value of transaction_detail.gmt_create
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_detail.gmt_create
     *
     * @param gmtCreate the value for transaction_detail.gmt_create
     *
     * @mbg.generated 2017-03-29 10:45:56
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}