package com.lawu.eshop.property.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class WithdrawCashDO implements Serializable {
    /**
     *
     * 主键
     * withdraw_cash.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * withdraw_cash.user_num
     *
     * @mbg.generated
     */
    private String userNum;

    /**
     *
     * 账号(冗余)
     * withdraw_cash.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * 名称(冗余)
     * withdraw_cash.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * 注册区域省ID(冗余)
     * withdraw_cash.province_id
     *
     * @mbg.generated
     */
    private Integer provinceId;

    /**
     *
     * 注册区域城市ID(冗余)
     * withdraw_cash.city_id
     *
     * @mbg.generated
     */
    private Integer cityId;

    /**
     *
     * 注册区域区ID(冗余)
     * withdraw_cash.area_id
     *
     * @mbg.generated
     */
    private Integer areaId;

    /**
     *
     * 提现金额
     * withdraw_cash.cash_money
     *
     * @mbg.generated
     */
    private BigDecimal cashMoney;

    /**
     *
     * 提现比例1:0.95
     * withdraw_cash.current_scale
     *
     * @mbg.generated
     */
    private String currentScale;

    /**
     *
     * 到账金额
     * withdraw_cash.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     *
     * 提现类型(1-用户提现2-商家提现)
     * withdraw_cash.user_type
     *
     * @mbg.generated
     */
    private Byte userType;

    /**
     *
     * 渠道（1-人工2-代付)
     * withdraw_cash.channel
     *
     * @mbg.generated
     */
    private Byte channel;

    /**
     *
     * 提现状态(1-申请中2-受理中3-提现成功4-提现失败)
     * withdraw_cash.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 提现银行卡关联ID
     * withdraw_cash.business_bank_account_id
     *
     * @mbg.generated
     */
    private Long businessBankAccountId;

    /**
     *
     * 提现单号
     * withdraw_cash.cash_number
     *
     * @mbg.generated
     */
    private String cashNumber;

    /**
     *
     * 第三方订单号(代付时存在)
     * withdraw_cash.third_number
     *
     * @mbg.generated
     */
    private String thirdNumber;

    /**
     *
     * 审核人ID
     * withdraw_cash.audit_user_id
     *
     * @mbg.generated
     */
    private Long auditUserId;

    /**
     *
     * 审核人姓名
     * withdraw_cash.audit_user_name
     *
     * @mbg.generated
     */
    private String auditUserName;

    /**
     *
     * 审核失败原因(冗余)
     * withdraw_cash.audit_faild_reason
     *
     * @mbg.generated
     */
    private String auditFaildReason;

    /**
     *
     * 备注
     * withdraw_cash.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * 
     * withdraw_cash.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * 
     * withdraw_cash.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table withdraw_cash
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.id
     *
     * @return the value of withdraw_cash.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.id
     *
     * @param id the value for withdraw_cash.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.user_num
     *
     * @return the value of withdraw_cash.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.user_num
     *
     * @param userNum the value for withdraw_cash.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.account
     *
     * @return the value of withdraw_cash.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.account
     *
     * @param account the value for withdraw_cash.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.name
     *
     * @return the value of withdraw_cash.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.name
     *
     * @param name the value for withdraw_cash.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.province_id
     *
     * @return the value of withdraw_cash.province_id
     *
     * @mbg.generated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.province_id
     *
     * @param provinceId the value for withdraw_cash.province_id
     *
     * @mbg.generated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.city_id
     *
     * @return the value of withdraw_cash.city_id
     *
     * @mbg.generated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.city_id
     *
     * @param cityId the value for withdraw_cash.city_id
     *
     * @mbg.generated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.area_id
     *
     * @return the value of withdraw_cash.area_id
     *
     * @mbg.generated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.area_id
     *
     * @param areaId the value for withdraw_cash.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.cash_money
     *
     * @return the value of withdraw_cash.cash_money
     *
     * @mbg.generated
     */
    public BigDecimal getCashMoney() {
        return cashMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.cash_money
     *
     * @param cashMoney the value for withdraw_cash.cash_money
     *
     * @mbg.generated
     */
    public void setCashMoney(BigDecimal cashMoney) {
        this.cashMoney = cashMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.current_scale
     *
     * @return the value of withdraw_cash.current_scale
     *
     * @mbg.generated
     */
    public String getCurrentScale() {
        return currentScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.current_scale
     *
     * @param currentScale the value for withdraw_cash.current_scale
     *
     * @mbg.generated
     */
    public void setCurrentScale(String currentScale) {
        this.currentScale = currentScale == null ? null : currentScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.money
     *
     * @return the value of withdraw_cash.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.money
     *
     * @param money the value for withdraw_cash.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.user_type
     *
     * @return the value of withdraw_cash.user_type
     *
     * @mbg.generated
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.user_type
     *
     * @param userType the value for withdraw_cash.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.channel
     *
     * @return the value of withdraw_cash.channel
     *
     * @mbg.generated
     */
    public Byte getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.channel
     *
     * @param channel the value for withdraw_cash.channel
     *
     * @mbg.generated
     */
    public void setChannel(Byte channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.status
     *
     * @return the value of withdraw_cash.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.status
     *
     * @param status the value for withdraw_cash.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.business_bank_account_id
     *
     * @return the value of withdraw_cash.business_bank_account_id
     *
     * @mbg.generated
     */
    public Long getBusinessBankAccountId() {
        return businessBankAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.business_bank_account_id
     *
     * @param businessBankAccountId the value for withdraw_cash.business_bank_account_id
     *
     * @mbg.generated
     */
    public void setBusinessBankAccountId(Long businessBankAccountId) {
        this.businessBankAccountId = businessBankAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.cash_number
     *
     * @return the value of withdraw_cash.cash_number
     *
     * @mbg.generated
     */
    public String getCashNumber() {
        return cashNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.cash_number
     *
     * @param cashNumber the value for withdraw_cash.cash_number
     *
     * @mbg.generated
     */
    public void setCashNumber(String cashNumber) {
        this.cashNumber = cashNumber == null ? null : cashNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.third_number
     *
     * @return the value of withdraw_cash.third_number
     *
     * @mbg.generated
     */
    public String getThirdNumber() {
        return thirdNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.third_number
     *
     * @param thirdNumber the value for withdraw_cash.third_number
     *
     * @mbg.generated
     */
    public void setThirdNumber(String thirdNumber) {
        this.thirdNumber = thirdNumber == null ? null : thirdNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.audit_user_id
     *
     * @return the value of withdraw_cash.audit_user_id
     *
     * @mbg.generated
     */
    public Long getAuditUserId() {
        return auditUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.audit_user_id
     *
     * @param auditUserId the value for withdraw_cash.audit_user_id
     *
     * @mbg.generated
     */
    public void setAuditUserId(Long auditUserId) {
        this.auditUserId = auditUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.audit_user_name
     *
     * @return the value of withdraw_cash.audit_user_name
     *
     * @mbg.generated
     */
    public String getAuditUserName() {
        return auditUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.audit_user_name
     *
     * @param auditUserName the value for withdraw_cash.audit_user_name
     *
     * @mbg.generated
     */
    public void setAuditUserName(String auditUserName) {
        this.auditUserName = auditUserName == null ? null : auditUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.audit_faild_reason
     *
     * @return the value of withdraw_cash.audit_faild_reason
     *
     * @mbg.generated
     */
    public String getAuditFaildReason() {
        return auditFaildReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.audit_faild_reason
     *
     * @param auditFaildReason the value for withdraw_cash.audit_faild_reason
     *
     * @mbg.generated
     */
    public void setAuditFaildReason(String auditFaildReason) {
        this.auditFaildReason = auditFaildReason == null ? null : auditFaildReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.remark
     *
     * @return the value of withdraw_cash.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.remark
     *
     * @param remark the value for withdraw_cash.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.gmt_create
     *
     * @return the value of withdraw_cash.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.gmt_create
     *
     * @param gmtCreate the value for withdraw_cash.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_cash.gmt_modified
     *
     * @return the value of withdraw_cash.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_cash.gmt_modified
     *
     * @param gmtModified the value for withdraw_cash.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}