package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.AddressDO;
import com.lawu.eshop.user.srv.domain.AddressDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AddressDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    int countByExample(AddressDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    int deleteByExample(AddressDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    int insert(AddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    int insertSelective(AddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    List<AddressDO> selectByExampleWithRowbounds(AddressDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    List<AddressDO> selectByExample(AddressDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    AddressDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    int updateByExampleSelective(@Param("record") AddressDO record, @Param("example") AddressDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    int updateByExample(@Param("record") AddressDO record, @Param("example") AddressDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    int updateByPrimaryKeySelective(AddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated 2017-03-27 10:54:42
     */
    int updateByPrimaryKey(AddressDO record);
}