package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.FavoriteMerchantDO;
import com.lawu.eshop.user.srv.domain.FavoriteMerchantDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FavoriteMerchantDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    int countByExample(FavoriteMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    int deleteByExample(FavoriteMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    int insert(FavoriteMerchantDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    int insertSelective(FavoriteMerchantDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    List<FavoriteMerchantDO> selectByExampleWithRowbounds(FavoriteMerchantDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    List<FavoriteMerchantDO> selectByExample(FavoriteMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    FavoriteMerchantDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    int updateByExampleSelective(@Param("record") FavoriteMerchantDO record, @Param("example") FavoriteMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    int updateByExample(@Param("record") FavoriteMerchantDO record, @Param("example") FavoriteMerchantDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    int updateByPrimaryKeySelective(FavoriteMerchantDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_merchant
     *
     * @mbg.generated 2017-03-24 10:29:55
     */
    int updateByPrimaryKey(FavoriteMerchantDO record);
}