package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.InviteRelationDO;
import com.lawu.eshop.user.srv.domain.InviteRelationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InviteRelationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    int countByExample(InviteRelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    int deleteByExample(InviteRelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    int insert(InviteRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    int insertSelective(InviteRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    List<InviteRelationDO> selectByExampleWithRowbounds(InviteRelationDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    List<InviteRelationDO> selectByExample(InviteRelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    InviteRelationDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    int updateByExampleSelective(@Param("record") InviteRelationDO record, @Param("example") InviteRelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    int updateByExample(@Param("record") InviteRelationDO record, @Param("example") InviteRelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    int updateByPrimaryKeySelective(InviteRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    int updateByPrimaryKey(InviteRelationDO record);
}