package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.MemberDO;
import com.lawu.eshop.user.srv.domain.MemberDOExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MemberDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    int countByExample(MemberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    int deleteByExample(MemberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    int insert(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    int insertSelective(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    List<MemberDO> selectByExampleWithRowbounds(MemberDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    List<MemberDO> selectByExample(MemberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    MemberDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    int updateByExampleSelective(@Param("record") MemberDO record, @Param("example") MemberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    int updateByExample(@Param("record") MemberDO record, @Param("example") MemberDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    int updateByPrimaryKeySelective(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    int updateByPrimaryKey(MemberDO record);
}