package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.MerchantStoreAuditDO;
import com.lawu.eshop.user.srv.domain.MerchantStoreAuditDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MerchantStoreAuditDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int countByExample(MerchantStoreAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int deleteByExample(MerchantStoreAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int insert(MerchantStoreAuditDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int insertSelective(MerchantStoreAuditDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    List<MerchantStoreAuditDO> selectByExampleWithBLOBsWithRowbounds(MerchantStoreAuditDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    List<MerchantStoreAuditDO> selectByExampleWithBLOBs(MerchantStoreAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    List<MerchantStoreAuditDO> selectByExampleWithRowbounds(MerchantStoreAuditDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    List<MerchantStoreAuditDO> selectByExample(MerchantStoreAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    MerchantStoreAuditDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int updateByExampleSelective(@Param("record") MerchantStoreAuditDO record, @Param("example") MerchantStoreAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int updateByExampleWithBLOBs(@Param("record") MerchantStoreAuditDO record, @Param("example") MerchantStoreAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int updateByExample(@Param("record") MerchantStoreAuditDO record, @Param("example") MerchantStoreAuditDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int updateByPrimaryKeySelective(MerchantStoreAuditDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int updateByPrimaryKeyWithBLOBs(MerchantStoreAuditDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    int updateByPrimaryKey(MerchantStoreAuditDO record);
}