package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.MerchantStoreProfileDO;
import com.lawu.eshop.user.srv.domain.MerchantStoreProfileDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MerchantStoreProfileDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    int countByExample(MerchantStoreProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    int deleteByExample(MerchantStoreProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    int insert(MerchantStoreProfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    int insertSelective(MerchantStoreProfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    List<MerchantStoreProfileDO> selectByExampleWithRowbounds(MerchantStoreProfileDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    List<MerchantStoreProfileDO> selectByExample(MerchantStoreProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    MerchantStoreProfileDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    int updateByExampleSelective(@Param("record") MerchantStoreProfileDO record, @Param("example") MerchantStoreProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    int updateByExample(@Param("record") MerchantStoreProfileDO record, @Param("example") MerchantStoreProfileDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    int updateByPrimaryKeySelective(MerchantStoreProfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_store_profile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    int updateByPrimaryKey(MerchantStoreProfileDO record);
}