package com.lawu.eshop.user.srv.mapper;

import com.lawu.eshop.user.srv.domain.TransactionRecordDO;
import com.lawu.eshop.user.srv.domain.TransactionRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TransactionRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    int countByExample(TransactionRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    int deleteByExample(TransactionRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    int insert(TransactionRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    int insertSelective(TransactionRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    List<TransactionRecordDO> selectByExampleWithRowbounds(TransactionRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    List<TransactionRecordDO> selectByExample(TransactionRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    TransactionRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    int updateByExampleSelective(@Param("record") TransactionRecordDO record, @Param("example") TransactionRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    int updateByExample(@Param("record") TransactionRecordDO record, @Param("example") TransactionRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    int updateByPrimaryKeySelective(TransactionRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_record
     *
     * @mbg.generated 2017-03-29 14:04:13
     */
    int updateByPrimaryKey(TransactionRecordDO record);
}