package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;

public class InviteRelationDO implements Serializable {
    /**
     *
     * 
     * invite_relation.id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Long id;

    /**
     *
     * 用户ID
     * invite_relation.user_id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Long userId;

    /**
     *
     * 被邀请者用户ID
     * invite_relation.invited_user_id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Long invitedUserId;

    /**
     *
     * 深度
     * invite_relation.depth
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Integer depth;

    /**
     *
     * 邀请类型
     * invite_relation.type
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table invite_relation
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_relation.id
     *
     * @return the value of invite_relation.id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_relation.id
     *
     * @param id the value for invite_relation.id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_relation.user_id
     *
     * @return the value of invite_relation.user_id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_relation.user_id
     *
     * @param userId the value for invite_relation.user_id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_relation.invited_user_id
     *
     * @return the value of invite_relation.invited_user_id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Long getInvitedUserId() {
        return invitedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_relation.invited_user_id
     *
     * @param invitedUserId the value for invite_relation.invited_user_id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setInvitedUserId(Long invitedUserId) {
        this.invitedUserId = invitedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_relation.depth
     *
     * @return the value of invite_relation.depth
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Integer getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_relation.depth
     *
     * @param depth the value for invite_relation.depth
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setDepth(Integer depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_relation.type
     *
     * @return the value of invite_relation.type
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_relation.type
     *
     * @param type the value for invite_relation.type
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setType(Byte type) {
        this.type = type;
    }
}