package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class MemberDO implements Serializable {
    /**
     *
     * 主键
     * member.id
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    private Long id;

    /**
     *
     * 登录账号
     * member.account
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    private String account;

    /**
     *
     * 登录密码
     * member.pwd
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    private String pwd;

    /**
     *
     * 手机号码
     * member.mobile
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    private String mobile;

    /**
     *
     * 创建时间
     * member.gmt_create
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    private Date gmtCreate;

    /**
     *
     * 修改时间
     * member.gmt_modified
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.account
     *
     * @return the value of member.account
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.account
     *
     * @param account the value for member.account
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pwd
     *
     * @return the value of member.pwd
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pwd
     *
     * @param pwd the value for member.pwd
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mobile
     *
     * @return the value of member.mobile
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mobile
     *
     * @param mobile the value for member.mobile
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gmt_create
     *
     * @return the value of member.gmt_create
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gmt_create
     *
     * @param gmtCreate the value for member.gmt_create
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gmt_modified
     *
     * @return the value of member.gmt_modified
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gmt_modified
     *
     * @param gmtModified the value for member.gmt_modified
     *
     * @mbg.generated 2017-03-13 11:11:22
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}