package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class MemberProfileDO implements Serializable {
    /**
     *
     * 主键，与member主键一致
     * member_profile.id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Long id;

    /**
     *
     * 邀请会员数
     * member_profile.invite_member_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Integer inviteMemberCount;

    /**
     *
     * 邀请商家数
     * member_profile.invite_merchant_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Integer inviteMerchantCount;

    /**
     *
     * 修改日期
     * member_profile.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Date gmtModified;

    /**
     *
     * 创建日期
     * member_profile.gmt_create
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_profile
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.id
     *
     * @return the value of member_profile.id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.id
     *
     * @param id the value for member_profile.id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.invite_member_count
     *
     * @return the value of member_profile.invite_member_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Integer getInviteMemberCount() {
        return inviteMemberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.invite_member_count
     *
     * @param inviteMemberCount the value for member_profile.invite_member_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setInviteMemberCount(Integer inviteMemberCount) {
        this.inviteMemberCount = inviteMemberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.invite_merchant_count
     *
     * @return the value of member_profile.invite_merchant_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Integer getInviteMerchantCount() {
        return inviteMerchantCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.invite_merchant_count
     *
     * @param inviteMerchantCount the value for member_profile.invite_merchant_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setInviteMerchantCount(Integer inviteMerchantCount) {
        this.inviteMerchantCount = inviteMerchantCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.gmt_modified
     *
     * @return the value of member_profile.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.gmt_modified
     *
     * @param gmtModified the value for member_profile.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_profile.gmt_create
     *
     * @return the value of member_profile.gmt_create
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_profile.gmt_create
     *
     * @param gmtCreate the value for member_profile.gmt_create
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}