package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class MemberDO implements Serializable {
    /**
     *
     * 主键
     * member.id
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private Long id;

    /**
     *
     * 会员编号
     * member.num
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private String num;

    /**
     *
     * 登录账号
     * member.account
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private String account;

    /**
     *
     * 登录密码
     * member.pwd
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private String pwd;

    /**
     *
     * 手机号码
     * member.mobile
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private String mobile;

    /**
     *
     * 姓名
     * member.name
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private String name;

    /**
     *
     * 昵称
     * member.nickname
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private String nickname;

    /**
     *
     * 地区路径
     * member.region_path
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private String regionPath;

    /**
     *
     * 性别 (0--男，2--女，1--保密)
     * member.sex
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private Byte sex;

    /**
     *
     * 出生年月
     * member.birthday
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private Date birthday;

    /**
     *
     * 头像
     * member.headimg
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private String headimg;

    /**
     *
     * 状态 (0--无效，1--有效)
     * member.status
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private Byte status;

    /**
     *
     * 邀请者ID
     * member.inviter_id
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private Long inviterId;

    /**
     *
     * 邀请者类型 (0--无推荐，1--会员，2--商户)
     * member.inviter_type
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private Byte inviterType;

    /**
     *
     * 等级
     * member.level
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private Integer level;

    /**
     *
     * 资金账户ID
     * member.property_id
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private Long propertyId;

    /**
     *
     * 修改时间
     * member.gmt_modified
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * member.gmt_create
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.num
     *
     * @return the value of member.num
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.num
     *
     * @param num the value for member.num
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.account
     *
     * @return the value of member.account
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.account
     *
     * @param account the value for member.account
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pwd
     *
     * @return the value of member.pwd
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pwd
     *
     * @param pwd the value for member.pwd
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mobile
     *
     * @return the value of member.mobile
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mobile
     *
     * @param mobile the value for member.mobile
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nickname
     *
     * @return the value of member.nickname
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nickname
     *
     * @param nickname the value for member.nickname
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.region_path
     *
     * @return the value of member.region_path
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public String getRegionPath() {
        return regionPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.region_path
     *
     * @param regionPath the value for member.region_path
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setRegionPath(String regionPath) {
        this.regionPath = regionPath == null ? null : regionPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sex
     *
     * @return the value of member.sex
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sex
     *
     * @param sex the value for member.sex
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birthday
     *
     * @return the value of member.birthday
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birthday
     *
     * @param birthday the value for member.birthday
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.headimg
     *
     * @return the value of member.headimg
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.headimg
     *
     * @param headimg the value for member.headimg
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg == null ? null : headimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.status
     *
     * @return the value of member.status
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.status
     *
     * @param status the value for member.status
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.inviter_id
     *
     * @return the value of member.inviter_id
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public Long getInviterId() {
        return inviterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.inviter_id
     *
     * @param inviterId the value for member.inviter_id
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setInviterId(Long inviterId) {
        this.inviterId = inviterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.inviter_type
     *
     * @return the value of member.inviter_type
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public Byte getInviterType() {
        return inviterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.inviter_type
     *
     * @param inviterType the value for member.inviter_type
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setInviterType(Byte inviterType) {
        this.inviterType = inviterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.level
     *
     * @return the value of member.level
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.level
     *
     * @param level the value for member.level
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.property_id
     *
     * @return the value of member.property_id
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public Long getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.property_id
     *
     * @param propertyId the value for member.property_id
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setPropertyId(Long propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gmt_modified
     *
     * @return the value of member.gmt_modified
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gmt_modified
     *
     * @param gmtModified the value for member.gmt_modified
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gmt_create
     *
     * @return the value of member.gmt_create
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gmt_create
     *
     * @param gmtCreate the value for member.gmt_create
     *
     * @mbg.generated 2017-03-31 08:54:39
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}