package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class MerchantProfileDO implements Serializable {
    /**
     *
     * 主键，与merchant主键一致
     * merchant_profile.id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Long id;

    /**
     *
     * 邀请会员数
     * merchant_profile.invite_member_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Integer inviteMemberCount;

    /**
     *
     * 邀请商家数
     * merchant_profile.invite_merchant_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Integer inviteMerchantCount;

    /**
     *
     * 官网链接
     * merchant_profile.website_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private String websiteUrl;

    /**
     *
     * 淘宝链接
     * merchant_profile.taobao_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private String taobaoUrl;

    /**
     *
     * 天猫链接
     * merchant_profile.tmall_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private String tmallUrl;

    /**
     *
     * 京东链接
     * merchant_profile.jd_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private String jdUrl;

    /**
     *
     * 修改日期
     * merchant_profile.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Date gmtModified;

    /**
     *
     * 创建日期
     * merchant_profile.gmt_create
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant_profile
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_profile.id
     *
     * @return the value of merchant_profile.id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_profile.id
     *
     * @param id the value for merchant_profile.id
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_profile.invite_member_count
     *
     * @return the value of merchant_profile.invite_member_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Integer getInviteMemberCount() {
        return inviteMemberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_profile.invite_member_count
     *
     * @param inviteMemberCount the value for merchant_profile.invite_member_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setInviteMemberCount(Integer inviteMemberCount) {
        this.inviteMemberCount = inviteMemberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_profile.invite_merchant_count
     *
     * @return the value of merchant_profile.invite_merchant_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Integer getInviteMerchantCount() {
        return inviteMerchantCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_profile.invite_merchant_count
     *
     * @param inviteMerchantCount the value for merchant_profile.invite_merchant_count
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setInviteMerchantCount(Integer inviteMerchantCount) {
        this.inviteMerchantCount = inviteMerchantCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_profile.website_url
     *
     * @return the value of merchant_profile.website_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public String getWebsiteUrl() {
        return websiteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_profile.website_url
     *
     * @param websiteUrl the value for merchant_profile.website_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl == null ? null : websiteUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_profile.taobao_url
     *
     * @return the value of merchant_profile.taobao_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public String getTaobaoUrl() {
        return taobaoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_profile.taobao_url
     *
     * @param taobaoUrl the value for merchant_profile.taobao_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setTaobaoUrl(String taobaoUrl) {
        this.taobaoUrl = taobaoUrl == null ? null : taobaoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_profile.tmall_url
     *
     * @return the value of merchant_profile.tmall_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public String getTmallUrl() {
        return tmallUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_profile.tmall_url
     *
     * @param tmallUrl the value for merchant_profile.tmall_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setTmallUrl(String tmallUrl) {
        this.tmallUrl = tmallUrl == null ? null : tmallUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_profile.jd_url
     *
     * @return the value of merchant_profile.jd_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public String getJdUrl() {
        return jdUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_profile.jd_url
     *
     * @param jdUrl the value for merchant_profile.jd_url
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setJdUrl(String jdUrl) {
        this.jdUrl = jdUrl == null ? null : jdUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_profile.gmt_modified
     *
     * @return the value of merchant_profile.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_profile.gmt_modified
     *
     * @param gmtModified the value for merchant_profile.gmt_modified
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_profile.gmt_create
     *
     * @return the value of merchant_profile.gmt_create
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_profile.gmt_create
     *
     * @param gmtCreate the value for merchant_profile.gmt_create
     *
     * @mbg.generated 2017-03-22 02:28:01
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}