package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MerchantStoreDO implements Serializable {
    /**
     *
     * 主键
     * merchant_store.id
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private Long id;

    /**
     *
     * 商家
     * merchant_store.merchant_id
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private Long merchantId;

    /**
     *
     * 店铺名称
     * merchant_store.name
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private String name;

    /**
     *
     * 省市区
     * merchant_store.region_path
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private String regionPath;

    /**
     *
     * 店铺地址信息
     * merchant_store.address
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private String address;

    /**
     *
     * 经度
     * merchant_store.longitude
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private BigDecimal longitude;

    /**
     *
     * 纬度
     * merchant_store.latitude
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private BigDecimal latitude;

    /**
     *
     * 主营业务
     * merchant_store.industry_path
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private String industryPath;

    /**
     *
     * 店铺介绍
     * merchant_store.intro
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private String intro;

    /**
     *
     * 0待审核 1审核通过 2审核不通过 3账号过期
     * merchant_store.status
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private Byte status;

    /**
     *
     * 负责人名字
     * merchant_store.principal_name
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private String principalName;

    /**
     *
     * 负责人手机
     * merchant_store.principal_mobile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private String principalMobile;

    /**
     *
     * 修改时间
     * merchant_store.gmt_modified
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * merchant_store.gmt_create
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant_store
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.id
     *
     * @return the value of merchant_store.id
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.id
     *
     * @param id the value for merchant_store.id
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.merchant_id
     *
     * @return the value of merchant_store.merchant_id
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.merchant_id
     *
     * @param merchantId the value for merchant_store.merchant_id
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.name
     *
     * @return the value of merchant_store.name
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.name
     *
     * @param name the value for merchant_store.name
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.region_path
     *
     * @return the value of merchant_store.region_path
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public String getRegionPath() {
        return regionPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.region_path
     *
     * @param regionPath the value for merchant_store.region_path
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setRegionPath(String regionPath) {
        this.regionPath = regionPath == null ? null : regionPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.address
     *
     * @return the value of merchant_store.address
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.address
     *
     * @param address the value for merchant_store.address
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.longitude
     *
     * @return the value of merchant_store.longitude
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.longitude
     *
     * @param longitude the value for merchant_store.longitude
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.latitude
     *
     * @return the value of merchant_store.latitude
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.latitude
     *
     * @param latitude the value for merchant_store.latitude
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.industry_path
     *
     * @return the value of merchant_store.industry_path
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public String getIndustryPath() {
        return industryPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.industry_path
     *
     * @param industryPath the value for merchant_store.industry_path
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setIndustryPath(String industryPath) {
        this.industryPath = industryPath == null ? null : industryPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.intro
     *
     * @return the value of merchant_store.intro
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.intro
     *
     * @param intro the value for merchant_store.intro
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.status
     *
     * @return the value of merchant_store.status
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.status
     *
     * @param status the value for merchant_store.status
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.principal_name
     *
     * @return the value of merchant_store.principal_name
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public String getPrincipalName() {
        return principalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.principal_name
     *
     * @param principalName the value for merchant_store.principal_name
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setPrincipalName(String principalName) {
        this.principalName = principalName == null ? null : principalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.principal_mobile
     *
     * @return the value of merchant_store.principal_mobile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public String getPrincipalMobile() {
        return principalMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.principal_mobile
     *
     * @param principalMobile the value for merchant_store.principal_mobile
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setPrincipalMobile(String principalMobile) {
        this.principalMobile = principalMobile == null ? null : principalMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.gmt_modified
     *
     * @return the value of merchant_store.gmt_modified
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.gmt_modified
     *
     * @param gmtModified the value for merchant_store.gmt_modified
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store.gmt_create
     *
     * @return the value of merchant_store.gmt_create
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store.gmt_create
     *
     * @param gmtCreate the value for merchant_store.gmt_create
     *
     * @mbg.generated 2017-03-24 17:37:11
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}