package com.lawu.eshop.user.srv.domain;

import java.io.Serializable;
import java.util.Date;

public class MerchantStoreAuditDO implements Serializable {
    /**
     *
     * 主键
     * merchant_store_audit.id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private Long id;

    /**
     *
     * 商家
     * merchant_store_audit.merchant_id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private Long merchantId;

    /**
     *
     * 门店
     * merchant_store_audit.merchant_store_id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private Long merchantStoreId;

    /**
     *
     * 审核状态
     * merchant_store_audit.status
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private Byte status;

    /**
     *
     * 审核人员ID
     * merchant_store_audit.auditor_id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private Integer auditorId;

    /**
     *
     * 审核备注
     * merchant_store_audit.remark
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private String remark;

    /**
     *
     * 审核时间
     * merchant_store_audit.audit_time
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private Date auditTime;

    /**
     *
     * 同步时间
     * merchant_store_audit.syn_time
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private Date synTime;

    /**
     *
     * 修改时间
     * merchant_store_audit.gmt_modified
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * merchant_store_audit.gmt_create
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private Date gmtCreate;

    /**
     *
     * 修改内容json
     * merchant_store_audit.content
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant_store_audit
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.id
     *
     * @return the value of merchant_store_audit.id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.id
     *
     * @param id the value for merchant_store_audit.id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.merchant_id
     *
     * @return the value of merchant_store_audit.merchant_id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.merchant_id
     *
     * @param merchantId the value for merchant_store_audit.merchant_id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.merchant_store_id
     *
     * @return the value of merchant_store_audit.merchant_store_id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public Long getMerchantStoreId() {
        return merchantStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.merchant_store_id
     *
     * @param merchantStoreId the value for merchant_store_audit.merchant_store_id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setMerchantStoreId(Long merchantStoreId) {
        this.merchantStoreId = merchantStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.status
     *
     * @return the value of merchant_store_audit.status
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.status
     *
     * @param status the value for merchant_store_audit.status
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.auditor_id
     *
     * @return the value of merchant_store_audit.auditor_id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public Integer getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.auditor_id
     *
     * @param auditorId the value for merchant_store_audit.auditor_id
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setAuditorId(Integer auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.remark
     *
     * @return the value of merchant_store_audit.remark
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.remark
     *
     * @param remark the value for merchant_store_audit.remark
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.audit_time
     *
     * @return the value of merchant_store_audit.audit_time
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.audit_time
     *
     * @param auditTime the value for merchant_store_audit.audit_time
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.syn_time
     *
     * @return the value of merchant_store_audit.syn_time
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public Date getSynTime() {
        return synTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.syn_time
     *
     * @param synTime the value for merchant_store_audit.syn_time
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setSynTime(Date synTime) {
        this.synTime = synTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.gmt_modified
     *
     * @return the value of merchant_store_audit.gmt_modified
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.gmt_modified
     *
     * @param gmtModified the value for merchant_store_audit.gmt_modified
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.gmt_create
     *
     * @return the value of merchant_store_audit.gmt_create
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.gmt_create
     *
     * @param gmtCreate the value for merchant_store_audit.gmt_create
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_store_audit.content
     *
     * @return the value of merchant_store_audit.content
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_store_audit.content
     *
     * @param content the value for merchant_store_audit.content
     *
     * @mbg.generated 2017-03-31 15:41:45
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}