package com.lawu.eshop.order.srv.mapper;

import com.lawu.eshop.order.srv.domain.shoppingCartDO;
import com.lawu.eshop.order.srv.domain.shoppingCartDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface shoppingCartDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    int countByExample(shoppingCartDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    int deleteByExample(shoppingCartDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    int insert(shoppingCartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    int insertSelective(shoppingCartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    List<shoppingCartDO> selectByExampleWithRowbounds(shoppingCartDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    List<shoppingCartDO> selectByExample(shoppingCartDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    shoppingCartDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    int updateByExampleSelective(@Param("record") shoppingCartDO record, @Param("example") shoppingCartDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    int updateByExample(@Param("record") shoppingCartDO record, @Param("example") shoppingCartDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    int updateByPrimaryKeySelective(shoppingCartDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated 2017-03-24 10:21:55
     */
    int updateByPrimaryKey(shoppingCartDO record);
}