package com.lawu.eshop.statistics.srv.mapper;

import com.lawu.eshop.statistics.srv.domain.ReportUserActiveAreaMonth;
import com.lawu.eshop.statistics.srv.domain.ReportUserActiveAreaMonthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportUserActiveAreaMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    int countByExample(ReportUserActiveAreaMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    int deleteByExample(ReportUserActiveAreaMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    int insert(ReportUserActiveAreaMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    int insertSelective(ReportUserActiveAreaMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    List<ReportUserActiveAreaMonth> selectByExampleWithRowbounds(ReportUserActiveAreaMonthExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    List<ReportUserActiveAreaMonth> selectByExample(ReportUserActiveAreaMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    ReportUserActiveAreaMonth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportUserActiveAreaMonth record, @Param("example") ReportUserActiveAreaMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportUserActiveAreaMonth record, @Param("example") ReportUserActiveAreaMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportUserActiveAreaMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user_active_area_month
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportUserActiveAreaMonth record);
}