package com.lawu.eshop.statistics.srv.mapper;

import com.lawu.eshop.statistics.srv.domain.ReportAreaPointConsumeMonth;
import com.lawu.eshop.statistics.srv.domain.ReportAreaPointConsumeMonthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportAreaPointConsumeMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    int countByExample(ReportAreaPointConsumeMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    int deleteByExample(ReportAreaPointConsumeMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    int insert(ReportAreaPointConsumeMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    int insertSelective(ReportAreaPointConsumeMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    List<ReportAreaPointConsumeMonth> selectByExampleWithRowbounds(ReportAreaPointConsumeMonthExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    List<ReportAreaPointConsumeMonth> selectByExample(ReportAreaPointConsumeMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    ReportAreaPointConsumeMonth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportAreaPointConsumeMonth record, @Param("example") ReportAreaPointConsumeMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportAreaPointConsumeMonth record, @Param("example") ReportAreaPointConsumeMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportAreaPointConsumeMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_month
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportAreaPointConsumeMonth record);
}