package com.lawu.eshop.statistics.srv.mapper;

import com.lawu.eshop.statistics.srv.domain.ReportAreaPointConsumeDaily;
import com.lawu.eshop.statistics.srv.domain.ReportAreaPointConsumeDailyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportAreaPointConsumeDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    int countByExample(ReportAreaPointConsumeDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    int deleteByExample(ReportAreaPointConsumeDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    int insert(ReportAreaPointConsumeDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    int insertSelective(ReportAreaPointConsumeDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    List<ReportAreaPointConsumeDaily> selectByExampleWithRowbounds(ReportAreaPointConsumeDailyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    List<ReportAreaPointConsumeDaily> selectByExample(ReportAreaPointConsumeDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    ReportAreaPointConsumeDaily selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReportAreaPointConsumeDaily record, @Param("example") ReportAreaPointConsumeDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReportAreaPointConsumeDaily record, @Param("example") ReportAreaPointConsumeDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportAreaPointConsumeDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_area_point_consume_daily
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportAreaPointConsumeDaily record);
}